name: Auto

on:
  push:
  schedule:
      - cron: "0 22 * * *"  # scheduled at 06:00 (UTC+8) everyday
jobs:
  build:
    runs-on: ubuntu-latest
    # if: github.ref == 'refs/heads/master'

    steps:
      - name: Checkout master
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: master
      - name: Set up python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Run app
        run: |
          python  main.py
